// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApi.Infrastructure.Persistence;

namespace OrderApi.Infrastructure.Migrations
{
    [DbContext(typeof(EntityEventContext))]
    partial class EntityEventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("OrderApi.Infrastructure.Persistence.EntityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EventData")
                        .HasColumnType("BLOB");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EntityEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
